# միայն զէնքով կայ հայոց փրկութիւն

# -------------------------------------------------------------------------------
# CONFIGURATION FOR PROTOBUSINESS
# -------------------------------------------------------------------------------

# Maximum decimal rate for tariffs (example: 0.20 = 20%)
# By default, this number is set to 0.20
tariffMaxRate: 0.20

# Is the market currently open?
# This is a boolean value, only accepting "true" and "false"
marketOpen: true

# Current conversion rates from gold to coins
# Example: 5 means 1 gold ingot = 5 coins, and vice versa
# By default, this number is set to 5
# THIS MUST BE AN INTEGER VALUE (NO DECIMALS)
goldStandard: 5