database:
    type: "mongo"
    host: "0.0.0.0"
    port: "27017"
    user: "youKnow"
    password: "YouKnowBetter"
    database: "bvt9uk8itwhrlwe"
    users-collection: "users"
    nations-collection: "nation"

redis:
    pubsub:
        channel: "PixliesCore"
    host: "localhost"
    password: ""
    port: 6379

server:
    name: ""
    displayName: ""

moderation:
    defaultReason: "No reason given."

joinQuit:
    joinMessage: "&8[&2&l+&8] &7%PLAYER%"
    quitMessage: "&8[&c&l-&8] &7%PLAYER%"

blockedWords: ["blockedword1"]

links:
    rules: "https://pixlies.net/rules"
    discord: "https://pixlies.net/discord"

# Only the first character is an emoji.
emojis:
    relax: '是'
    mad: '了'
    really: '不'
    amogus: '在'
    pog: '码'

chat:
    formatting: true
    # You can use PlaceholderAPI placeholders.
    # %player% The player's username
    # %nickname% The player's nickname
    # %message% The message sent
    format: "%luckperms_prefix%%nickname%%luckperms_suffix%&7: &f%message%"

commands:
    # Enable if the plugin is loaded on a lobby server or equivalent
    limitedCommands: false

scoreboard:
    enabled: true

warpSettings:
    timedTeleports: true

tablist:
    ranks:
        ruby:
            order: 1110
        sapphire:
            order: 1100
        amethyst:
            order: 1090
        topaz:
            order: 1080
        default:
            order: 1070
        youtuber:
            order: 1060
        builder:
            order: 1050
        helper:
            order: 1040
        mod:
            order: 1030
        admin:
            order: 1020
        dev:
            order: 1010
        manager:
            order: 1000

combat:
    timer: true

warps:
    spawn:
        name: "Spawn"
        description: "The spawn."
        material: "BEACON"