warps:
  pvp:
    name: "PvP"
    description: "Teleport to the PvP arena!"
    material: "NETHERITE_SWORD"

walkspeed:
  level: 1

servers:
  Earth:
    max-players: 200

join_leave:
  join_message: |-
    &r
    &r&x&4&E&D&E&D&B&lP&r&x&4&D&C&9&C&7&li&r&x&4&1&B&0&A&E&lx&r&x&3&B&A&1&9&F&ll&r&x&3&4&8&C&8&B&li&r&x&3&0&7&A&7&A&le&r&x&2&9&6&9&6&9&ls&r&x&9&C&9&C&9&C&lN&r&x&A&8&A&8&A&8&le&r&x&A&D&A&D&A&D&lt&r&x&B&3&B&3&B&3&lw&r&x&B&D&B&D&B&D&lo&r&x&D&4&D&4&D&4&lr&r&f&lk&r&7!
    &7Right click on the banner to get started on your journey.
    &7Remember to join our Discord server at &bpixlies.net/discord&7!
    &r