package net.pixlies.nations.nations.customization;

public enum Ideology {

    AUTOCRATIC_EMPIRE,
    OLIGARCHIC_EMPIRE,
    CONSERVATIVE_REPUBLIC,
    LIBERAL_REPUBLIC,
    SOCIAL_DEMOCRATIC_REPUBLIC,
    FASCIST_REPUBLIC,
    COMMUNIST_REPUBLIC,
    FEUDAL_MONARCHY,
    ABSOLUTE_MONARCHY,
    CONSTITUTIONAL_MONARCHY,
    THEOCRACY,
    TRIBAL

}
